title: Nexus
description: News And Reports On Consumer Technology Breakthroughs And Shows You What's New On Serious Current News To Get The Most Out Of The Tech In Your Life

url:
baseurl:
paginate_path: /:num/
permalink: /:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 8

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"

gems: 
      - jekyll-sitemap